// Deployed Worker entry. Wrangler bundles from here (see wrangler.jsonc `main`).
//
// It re-exports two things into the single Worker script:
//   1. OpenNext's generated request handler (the whole Next.js app) as default.
//   2. The GenerateBaby Workflow class, so the `GENERATE_BABY` binding resolves.
//
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`, which
// runs before `wrangler dev`/`wrangler deploy` via the npm scripts.

// @ts-expect-error generated by `opennextjs-cloudflare build`
export { default } from "./.open-next/worker.js";

export { GenerateBaby } from "./src/workflows/generate-baby";
